import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'si' | 'ta';

export interface LanguageContextType {
  currentLanguage: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

interface LanguageProviderProps {
  children: ReactNode;
}

// Translation dictionaries
const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.taxi': 'Taxi',
    'nav.food': 'Food',
    'nav.parcel': 'Parcel',
    'nav.breakdown': 'Breakdown',
    'nav.dashboard': 'Dashboard',
    'nav.lorry': 'Lorry',
    'nav.movers': 'Movers',
    'nav.supermarket': 'Supermarket',
    'nav.gas': 'Gas',
    'nav.bus': 'Bus',
    'nav.jcb': 'JCB',
    
    // Common
    'common.loading': 'Loading...',
    'common.submit': 'Submit',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.confirm': 'Confirm',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.close': 'Close',
    'common.open': 'Open',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.viewAll': 'View All',
    'common.getStarted': 'Get Started',
    'common.learnMore': 'Learn More',
    'common.tryNow': 'Try Now',
    'common.bookNow': 'Book Now',
    'common.orderNow': 'Order Now',
    'common.sendNow': 'Send Now',
    'common.success': 'Success',
    'common.error': 'Error',
    'common.warning': 'Warning',
    'common.info': 'Information',
    'common.comingSoon': 'SOON',
    
    // Home page
    'home.title': 'Fresh Multi-Service Platform',
    'home.subtitle': 'Get rides, food delivery, parcel services, and breakdown assistance all in one app',
    'home.heroSubtitle': 'Everything. Everywhere.',
    'home.services.taxi': 'Taxi Rides',
    'home.services.taxi.desc': 'Fast, reliable rides across Sri Lanka. Book now and get there safely.',
    'home.services.food': 'Food Delivery',
    'home.services.food.desc': 'Discover amazing restaurants. Fresh meals delivered hot with live tracking and fast delivery.',
    'home.services.parcel': 'Parcel Delivery',
    'home.services.parcel.desc': 'Send anything, anywhere. Secure packaging, real-time tracking, and doorstep delivery guarantee.',
    'home.services.movers': 'Movers',
    'home.services.movers.desc': 'Professional home and office moving services. Safe, reliable goods removals with experienced team and full insurance coverage.',
    'home.services.breakdown': 'Breakdown Services',
    'home.features.title': 'Why Choose Run Pick?',
    'home.features.reliable': 'Reliable Service',
    'home.features.reliable.desc': '24/7 available services with verified drivers and partners',
    'home.features.tracking': 'Real-time Tracking',
    'home.features.tracking.desc': 'Track your ride, food order, or parcel in real-time',
    'home.features.payment': 'Secure Payment',
    'home.features.payment.desc': 'Multiple payment options with secure transactions',
    
    // Authentication
    'auth.welcome': 'Welcome to Run Pick',
    'auth.subtitle': 'Your everything app for Sri Lanka',
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.signInTitle': 'Welcome Back',
    'auth.signUpTitle': 'Create Account',
    'auth.signInSubtitle': 'Sign in to your account to continue',
    'auth.signUpSubtitle': 'Create your account to get started',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.name': 'Full Name',
    'auth.phone': 'Phone Number',
    'auth.role': 'Account Type',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.noAccount': 'Don\'t have an account?',
    'auth.hasAccount': 'Already have an account?',
    'auth.createAccount': 'Create Account',
    'auth.signInInstead': 'Sign in instead',
    'auth.signUpInstead': 'Sign up instead',
    'auth.roleCustomer': 'Customer',
    'auth.roleDriver': 'Driver',
    'auth.roleVendor': 'Vendor',
    'auth.roleAdmin': 'Admin',
    'auth.roleCustomer.desc': 'Book rides, order food, send parcels',
    'auth.roleDriver.desc': 'Drive passengers, deliver food & parcels',
    'auth.roleVendor.desc': 'Manage restaurants and food delivery',
    'auth.roleAdmin.desc': 'Manage platform operations',
    'auth.adminCode': 'Admin Secret Code',
    'auth.adminCode.placeholder': 'Enter admin secret code',
    'auth.adminCode.required': 'Admin secret code is required',
    'auth.error.invalidCredentials': 'Invalid email or password',
    'auth.error.userExists': 'User already exists',
    'auth.error.invalidAdmin': 'Invalid admin secret code',
    
    // Dashboard - Customer
    'dashboard.customer.title': 'Customer Dashboard',
    'dashboard.customer.subtitle': 'Manage your bookings and orders',
    'dashboard.customer.totalRides': 'Total Rides',
    'dashboard.customer.foodOrders': 'Food Orders',
    'dashboard.customer.parcelsSent': 'Parcels Sent',
    'dashboard.customer.walletBalance': 'Wallet Balance',
    'dashboard.customer.recentActivity': 'Recent Activity',
    'dashboard.customer.favoriteRestaurants': 'Favorite Restaurants',
    'dashboard.customer.frequentRoutes': 'Frequent Routes',
    'dashboard.customer.bookRide': 'Book a Ride',
    'dashboard.customer.orderFood': 'Order Food',
    'dashboard.customer.sendParcel': 'Send Parcel',
    
    // Dashboard - Driver
    'dashboard.driver.title': 'Driver Dashboard',
    'dashboard.driver.subtitle': 'Manage your rides and earnings',
    'dashboard.driver.todaysEarnings': 'Today\'s Earnings',
    'dashboard.driver.completedRides': 'Completed Rides',
    'dashboard.driver.rating': 'Rating',
    'dashboard.driver.thisWeek': 'This Week',
    'dashboard.driver.activeRequests': 'Active Requests',
    'dashboard.driver.recentTrips': 'Recent Trips',
    'dashboard.driver.goOnline': 'Go Online',
    'dashboard.driver.goOffline': 'Go Offline',
    'dashboard.driver.acceptRequest': 'Accept',
    'dashboard.driver.declineRequest': 'Decline',
    'dashboard.driver.online': 'Online',
    'dashboard.driver.offline': 'Offline',
    
    // Dashboard - Vendor
    'dashboard.vendor.title': 'Vendor Dashboard',
    'dashboard.vendor.subtitle': 'Manage your restaurants and orders',
    'dashboard.vendor.totalRevenue': 'Total Revenue',
    'dashboard.vendor.ordersToday': 'Orders Today',
    'dashboard.vendor.averageRating': 'Average Rating',
    'dashboard.vendor.deliveryTime': 'Delivery Time',
    'dashboard.vendor.restaurants': 'My Restaurants',
    'dashboard.vendor.recentOrders': 'Recent Orders',
    'dashboard.vendor.addRestaurant': 'Add Restaurant',
    'dashboard.vendor.manageMenu': 'Manage Menu',
    
    // Dashboard - Admin
    'dashboard.admin.title': 'Admin Dashboard',
    'dashboard.admin.subtitle': 'Manage platform operations',
    'dashboard.admin.totalUsers': 'Total Users',
    'dashboard.admin.activeDrivers': 'Active Drivers',
    'dashboard.admin.totalRevenue': 'Total Revenue',
    'dashboard.admin.commission': 'Commission',
    'dashboard.admin.recentActivity': 'Recent Activity',
    'dashboard.admin.pendingApprovals': 'Pending Approvals',
    'dashboard.admin.systemStats': 'System Statistics',
    'dashboard.admin.userManagement': 'User Management',
    'dashboard.admin.driverApprovals': 'Driver Approvals',
    'dashboard.admin.vendorApprovals': 'Vendor Approvals',
    
    // Ride booking
    'ride.title': 'Book a Ride',
    'ride.pickup': 'Pickup Location',
    'ride.destination': 'Destination',
    'ride.currentLocation': 'Use Current Location',
    'ride.chooseVehicle': 'Choose Vehicle Type',
    'ride.availableDrivers': 'Available Drivers',
    'ride.confirmBooking': 'Confirm Booking',
    'ride.requestRide': 'Request Ride',
    'ride.booking': 'Booking...',
    'ride.estimatedFare': 'Estimated Fare',
    'ride.duration': 'Duration',
    'ride.distance': 'Distance',
    'ride.vehicleType.bike': 'Motorcycle',
    'ride.vehicleType.tuktuk': 'Tuk-Tuk',
    'ride.vehicleType.car': 'Car',
    'ride.vehicleType.van': 'Van',
    'ride.status.pending': 'Pending',
    'ride.status.accepted': 'Accepted',
    'ride.status.arrived': 'Driver Arrived',
    'ride.status.started': 'Trip Started',
    'ride.status.completed': 'Completed',
    'ride.status.cancelled': 'Cancelled',
    
    // Food delivery
    'food.title': 'Food Delivery',
    'food.browseRestaurants': 'Browse Restaurants',
    'food.orderHistory': 'Order History',
    'food.favorites': 'Favorites',
    'food.trackOrder': 'Track Order',
    'food.addToCart': 'Add to Cart',
    'food.viewCart': 'View Cart',
    'food.checkout': 'Checkout',
    'food.orderPlaced': 'Order Placed',
    'food.estimatedDelivery': 'Estimated Delivery',
    'food.restaurant.closed': 'Restaurant Closed',
    'food.restaurant.open': 'Open Now',
    'food.status.preparing': 'Preparing',
    'food.status.ready': 'Ready for Pickup',
    'food.status.pickedUp': 'Picked Up',
    'food.status.delivered': 'Delivered',
    
    // Parcel delivery
    'parcel.title': 'Parcel Delivery',
    'parcel.senderInfo': 'Sender Information',
    'parcel.receiverInfo': 'Receiver Information',
    'parcel.packageDetails': 'Package Details',
    'parcel.deliveryOptions': 'Delivery Options',
    'parcel.schedulePickup': 'Schedule Pickup',
    'parcel.trackParcel': 'Track Parcel',
    'parcel.deliveryFee': 'Delivery Fee',
    'parcel.packageWeight': 'Package Weight',
    'parcel.packageSize': 'Package Size',
    'parcel.specialInstructions': 'Special Instructions',
    'parcel.status.pickedUp': 'Picked Up',
    'parcel.status.inTransit': 'In Transit',
    'parcel.status.outForDelivery': 'Out for Delivery',
    'parcel.status.delivered': 'Delivered',
    
    // Status and messages
    'status.active': 'Active',
    'status.inactive': 'Inactive',
    'status.pending': 'Pending',
    'status.approved': 'Approved',
    'status.rejected': 'Rejected',
    'status.completed': 'Completed',
    'status.cancelled': 'Cancelled',
    'status.online': 'Online',
    'status.offline': 'Offline',
    
    // Footer
    'footer.services': 'Services',
    'footer.partners': 'Partners',
    'footer.contact': 'Contact Us',
    'footer.accessibility': 'Accessibility',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.cookies': 'Cookies',
    'footer.copyright': '© 2024 Run Pick. All rights reserved.',
    'footer.tagline': 'Everything. Everywhere.',
    
    // Language selector
    'language.selector': 'Language',
    'language.english': 'English',
    'language.sinhala': 'සිංහල',
    'language.tamil': 'தமிழ்',
    
    // Buttons and actions
    'button.becomePartner': 'Become a Partner',
    'button.signOut': 'Sign Out',
    'button.approve': 'Approve',
    'button.reject': 'Reject',
    'button.view': 'View',
    'button.manage': 'Manage',
    'button.update': 'Update',
    'button.refresh': 'Refresh',
    
    // Time and dates
    'time.now': 'Now',
    'time.today': 'Today',
    'time.yesterday': 'Yesterday',
    'time.thisWeek': 'This Week',
    'time.thisMonth': 'This Month',
    'time.ago': 'ago',
    'time.mins': 'mins',
    'time.hours': 'hours',
    'time.days': 'days',
  },
  
  si: {
    // Navigation
    'nav.home': 'මුල් පිටුව',
    'nav.taxi': 'ටැක්සි',
    'nav.food': 'ආහාර',
    'nav.parcel': 'පාර්සල්',
    'nav.breakdown': 'බිඳවැටීම්',
    'nav.dashboard': 'ඩෑෂ්බෝඩ්',
    'nav.lorry': 'ලොරි',
    'nav.movers': 'ගෙන්වන්නන්',
    'nav.supermarket': 'සුපර්මාකට්',
    'nav.gas': 'ගෑස්',
    'nav.bus': 'බස්',
    'nav.jcb': 'ජේසීබී',
    
    // Common
    'common.loading': 'පූරණය වෙමින්...',
    'common.submit': 'ඉදිරිපත් කරන්න',
    'common.cancel': 'අවලංගු කරන්න',
    'common.save': 'සුරකින්න',
    'common.edit': 'සංස්කරණය',
    'common.delete': 'මකන්න',
    'common.confirm': 'තහවුරු කරන්න',
    'common.back': 'ආපසු',
    'common.next': 'ඊළඟ',
    'common.previous': 'පෙර',
    'common.search': 'සෙවීම',
    'common.filter': 'පෙරහන',
    'common.close': 'වසන්න',
    'common.open': 'විවෘත කරන්න',
    'common.yes': 'ඔව්',
    'common.no': 'නැත',
    'common.viewAll': 'සියල්ල බලන්න',
    'common.getStarted': 'ආරම්භ කරන්න',
    'common.learnMore': 'වැඩිදුර ඉගෙන ගන්න',
    'common.tryNow': 'දැන් උත්සාහ කරන්න',
    'common.bookNow': 'දැන් වෙන් කරන්න',
    'common.orderNow': 'දැන් ඇණවුම් කරන්න',
    'common.sendNow': 'දැන් යවන්න',
    'common.success': 'සාර්ථකයි',
    'common.error': 'දෝෂයක්',
    'common.warning': 'අනතුරු ඇඟවීමක්',
    'common.info': 'තොරතුර',
    'common.comingSoon': 'ළඟදීම',
    
    // Home page
    'home.title': 'නව බහු-සේවා වේදිකාව',
    'home.subtitle': 'එක් යෙදුමකින් රයිඩ්, ආහාර බෙදාහැරීම, පාර්සල් සේවා සහ බිඳවැටීම් සහාය ලබා ගන්න',
    'home.heroSubtitle': 'සෑම දෙයක්ම. සෑම තැනකම.',
    'home.services.taxi': 'ටැක්සි රයිඩ්',
    'home.services.taxi.desc': 'ශ්‍රී ලංකාව පුරා වේගවත්, විශ්වසනීය රයිඩ්. දැන් වෙන් කර ආරක්ෂිතව ගමන් කරන්න.',
    'home.services.food': 'ආහාර බෙදාහැරීම',
    'home.services.food.desc': 'විස්මිත අවන්හල් සොයා ගන්න. නිරතුරු ලුහුබැඳීම සහ වේගවත් බෙදාහැරීම සමඟ නැවුම් ආහාර රස්නයෙන්.',
    'home.services.parcel': 'පාර්සල් බෙදාහැරීම',
    'home.services.parcel.desc': 'ඕනෑම දෙයක්, ඕනෑම තැනකට යවන්න. ආරක්ෂිත ඇසුරුම්, නිරතුරු ලුහුබැඳීම සහ දොරට බෙදාහැරීමේ සහතිකය.',
    'home.services.movers': 'ගෙන්වන්නන්',
    'home.services.movers.desc': 'වෘත්තීය ගෘහ හා කාර්යාල ගෙන්වීමේ සේවා. පළපුරුදු කණ්ඩායම සහ සම්පූර්ණ රක්ෂණ ආවරණයක් සමඟ ආරක්ෂිත, විශ්වසනීය භාණ්ඩ ඉවත් කිරීම.',
    'home.services.breakdown': 'බිඳවැටීම් සේවා',
    'home.features.title': 'ඇයි Run Pick තෝරන්නේ?',
    'home.features.reliable': 'විශ්වසනීය සේවාව',
    'home.features.reliable.desc': 'සත්‍යාපිත රියදුරන් සහ හවුල්කරුවන් සමඟ 24/7 ලබා ගත හැකි සේවා',
    'home.features.tracking': 'නිරතුරු ලුහුබැඳීම',
    'home.features.tracking.desc': 'ඔබේ රයිඩ්, ආහාර ඇණවුම, හෝ පාර්සල් නිරතුරුව ලුහුබඳින්න',
    'home.features.payment': 'ආරක්ෂිත ගෙවීම',
    'home.features.payment.desc': 'ආරක්ෂිත ගණුදෙනු සමඟ බහුවිධ ගෙවීමේ විකල්ප',
    
    // Authentication
    'auth.welcome': 'Run Pick වෙත සාදරයෙන් පිළිගනිමු',
    'auth.subtitle': 'ශ්‍රී ලංකාව සඳහා ඔබේ සියල්ල යෙදුම',
    'auth.signIn': 'පුරන්න',
    'auth.signUp': 'ලියාපදිංචි වන්න',
    'auth.signInTitle': 'නැවත සාදරයෙන් පිළිගනිමු',
    'auth.signUpTitle': 'ගිණුමක් සාදන්න',
    'auth.signInSubtitle': 'දිගටම කරගෙන යාමට ඔබේ ගිණුමට පුරන්න',
    'auth.signUpSubtitle': 'ආරම්භ කිරීමට ඔබේ ගිණුම සාදන්න',
    'auth.email': 'ඊමේල්',
    'auth.password': 'මුරපදය',
    'auth.confirmPassword': 'මුරපදය තහවුරු කරන්න',
    'auth.name': 'සම්පූර්ණ නම',
    'auth.phone': 'දුරකථන අංකය',
    'auth.role': 'ගිණුම් වර්ගය',
    'auth.forgotPassword': 'මුරපදය අමතකද?',
    'auth.noAccount': 'ගිණුමක් නැද්ද?',
    'auth.hasAccount': 'දැනටමත් ගිණුමක් තිබේද?',
    'auth.createAccount': 'ගිණුමක් සාදන්න',
    'auth.signInInstead': 'ඒ වෙනුවට පුරන්න',
    'auth.signUpInstead': 'ඒ වෙනුවට ලියාපදිංචි වන්න',
    'auth.roleCustomer': 'පාරිභෝගිකයා',
    'auth.roleDriver': 'රියදුරු',
    'auth.roleVendor': 'විකුණුම්කරු',
    'auth.roleAdmin': 'පරිපාලක',
    'auth.roleCustomer.desc': 'රයිඩ් වෙන් කරන්න, ආහාර ඇණවුම් කරන්න, පාර්සල් යවන්න',
    'auth.roleDriver.desc': 'මගීන් ගෙන යන්න, ආහාර සහ පාර්සල් බෙදා හරින්න',
    'auth.roleVendor.desc': 'අවන්හල් සහ ආහාර බෙදාහැරීම කළමනාකරණය කරන්න',
    'auth.roleAdmin.desc': 'වේදිකා මෙහෙයුම් කළමනාකරණය කරන්න',
    'auth.adminCode': 'පරිපාලක රහස් කේතය',
    'auth.adminCode.placeholder': 'පරිපාලක රහස් කේතය ඇතුළත් කරන්න',
    'auth.adminCode.required': 'පරිපාලක රහස් කේතය අවශ්‍යයි',
    'auth.error.invalidCredentials': 'වලංගු නොවන ඊමේල් හෝ මුරපදය',
    'auth.error.userExists': 'පරිශීලකයා දැනටමත් පවතී',
    'auth.error.invalidAdmin': 'වලංගු නොවන පරිපාලක රහස් කේතය',
    
    // Dashboard - Customer
    'dashboard.customer.title': 'පාරිභෝගික ඩෑෂ්බෝඩ්',
    'dashboard.customer.subtitle': 'ඔබේ වෙන්කිරීම් සහ ඇණවුම් කළමනාකරණය කරන්න',
    'dashboard.customer.totalRides': 'මුළු රයිඩ්',
    'dashboard.customer.foodOrders': 'ආහාර ඇණවුම්',
    'dashboard.customer.parcelsSent': 'යැවූ පාර්සල්',
    'dashboard.customer.walletBalance': 'පසුම්බියේ ශේෂය',
    'dashboard.customer.recentActivity': 'මෑත ක්‍රියාකාරකම්',
    'dashboard.customer.favoriteRestaurants': 'ප්‍රියතම අවන්හල්',
    'dashboard.customer.frequentRoutes': 'නිතර යන මාර්ග',
    'dashboard.customer.bookRide': 'රයිඩ් එකක් වෙන් කරන්න',
    'dashboard.customer.orderFood': 'ආහාර ඇණවුම් කරන්න',
    'dashboard.customer.sendParcel': 'පාර්සල් යවන්න',
    
    // Dashboard - Driver
    'dashboard.driver.title': 'රියදුරු ඩෑෂ්බෝඩ්',
    'dashboard.driver.subtitle': 'ඔබේ රයිඩ් සහ ආදායම කළමනාකරණය කරන්න',
    'dashboard.driver.todaysEarnings': 'අදයේ ආදායම',
    'dashboard.driver.completedRides': 'සම්පූර්ණ කළ රයිඩ්',
    'dashboard.driver.rating': 'ශ්‍රේණිගත කිරීම',
    'dashboard.driver.thisWeek': 'මෙම සතිය',
    'dashboard.driver.activeRequests': 'සක්‍රිය ඉල්ලීම්',
    'dashboard.driver.recentTrips': 'මෑත සන්දමන්',
    'dashboard.driver.goOnline': 'අන්තර්ජාලීන වන්න',
    'dashboard.driver.goOffline': 'අන්තර්ජාලීන නොවන්න',
    'dashboard.driver.acceptRequest': 'පිළිගන්න',
    'dashboard.driver.declineRequest': 'ප්‍රතික්ෂේප කරන්න',
    'dashboard.driver.online': 'අන්තර්ජාලීන',
    'dashboard.driver.offline': 'අන්තර්ජාලීන නොවේ',
    
    // Dashboard - Vendor
    'dashboard.vendor.title': 'විකුණුම්කරු ඩෑෂ්බෝඩ්',
    'dashboard.vendor.subtitle': 'ඔබේ අවන්හල් සහ ඇණවුම් කළමනාකරණය කරන්න',
    'dashboard.vendor.totalRevenue': 'මුළු ආදායම',
    'dashboard.vendor.ordersToday': 'අදයේ ඇණවුම්',
    'dashboard.vendor.averageRating': 'සාමාන්‍ය ශ්‍රේණිගත කිරීම',
    'dashboard.vendor.deliveryTime': 'බෙදාහැරීමේ කාලය',
    'dashboard.vendor.restaurants': 'මගේ අවන්හල්',
    'dashboard.vendor.recentOrders': 'මෑත ඇණවුම්',
    'dashboard.vendor.addRestaurant': 'අවන්හල එකක් එකතු කරන්න',
    'dashboard.vendor.manageMenu': 'මෙනුව කළමනාකරණය කරන්න',
    
    // Dashboard - Admin
    'dashboard.admin.title': 'පරිපාලක ඩෑෂ්බෝඩ්',
    'dashboard.admin.subtitle': 'වේදිකා මෙහෙයුම් කළමනාකරණය කරන්න',
    'dashboard.admin.totalUsers': 'මුළු පරිශීලකයින්',
    'dashboard.admin.activeDrivers': 'සක්‍රිය රියදුරන්',
    'dashboard.admin.totalRevenue': 'මුළු ආදායම',
    'dashboard.admin.commission': 'කොමිසම',
    'dashboard.admin.recentActivity': 'මෑත ක්‍රියාකාරකම්',
    'dashboard.admin.pendingApprovals': 'අනුමැතිය සඳහා රඳී සිටින',
    'dashboard.admin.systemStats': 'පද්ධති සංඛ්‍යාලේඛන',
    'dashboard.admin.userManagement': 'පරිශීලක කළමනාකරණය',
    'dashboard.admin.driverApprovals': 'රියදුරු අනුමැතිය',
    'dashboard.admin.vendorApprovals': 'විකුණුම්කරු අනුමැතිය',
    
    // Ride booking
    'ride.title': 'රයිඩ් එකක් වෙන් කරන්න',
    'ride.pickup': 'ගත් කරන ස්ථානය',
    'ride.destination': 'ගමනාන්තය',
    'ride.currentLocation': 'වත්මන් ස්ථානය භාවිතා කරන්න',
    'ride.chooseVehicle': 'වාහන වර්ගය තෝරන්න',
    'ride.availableDrivers': 'ලබා ගත හැකි රියදුරන්',
    'ride.confirmBooking': 'වෙන් කිරීම තහවුරු කරන්න',
    'ride.requestRide': 'රයිඩ් ඉල්ලන්න',
    'ride.booking': 'වෙන් කරමින්...',
    'ride.estimatedFare': 'ඇස්තමේන්තුගත ගාස්තුව',
    'ride.duration': 'කාල සීමාව',
    'ride.distance': 'දුර',
    'ride.vehicleType.bike': 'යතුරුපැදිය',
    'ride.vehicleType.tuktuk': 'ටුක්-ටුක්',
    'ride.vehicleType.car': 'කාර්',
    'ride.vehicleType.van': 'වෑන්',
    'ride.status.pending': 'පොරොත්තුවෙන්',
    'ride.status.accepted': 'පිළිගත්',
    'ride.status.arrived': 'රියදුරු පැමිණ ඇත',
    'ride.status.started': 'ගමන ආරම්භ විය',
    'ride.status.completed': 'සම්පූර්ණයි',
    'ride.status.cancelled': 'අවලංගු විය',
    
    // Food delivery
    'food.title': 'ආහාර බෙදාහැරීම',
    'food.browseRestaurants': 'අවන්හල් පිරික්සන්න',
    'food.orderHistory': 'ඇණවුම් ඉතිහාසය',
    'food.favorites': 'ප්‍රියතම',
    'food.trackOrder': 'ඇණවුම ලුහුබඳින්න',
    'food.addToCart': 'කරට එකතු කරන්න',
    'food.viewCart': 'කරත් බලන්න',
    'food.checkout': 'ගෙවීම',
    'food.orderPlaced': 'ඇණවුම දැමූ',
    'food.estimatedDelivery': 'ඇස්තමේන්තුගත බෙදාහැරීම',
    'food.restaurant.closed': 'අවන්හල වසා ඇත',
    'food.restaurant.open': 'දැන් විවෘත',
    'food.status.preparing': 'සකස් කරමින්',
    'food.status.ready': 'ගැනීමට සූදානම්',
    'food.status.pickedUp': 'ගෙන ගත්',
    'food.status.delivered': 'බෙදා හරින ලදි',
    
    // Parcel delivery
    'parcel.title': 'පාර්සල් බෙදාහැරීම',
    'parcel.senderInfo': 'යවන්නාගේ තොරතුරු',
    'parcel.receiverInfo': 'ලබන්නාගේ තොරතුරු',
    'parcel.packageDetails': 'පැකේජ විස්තර',
    'parcel.deliveryOptions': 'බෙදාහැරීමේ විකල්ප',
    'parcel.schedulePickup': 'ගැනීම නියම කරන්න',
    'parcel.trackParcel': 'පාර්සල් ලුහුබඳින්න',
    'parcel.deliveryFee': 'බෙදාහැරීමේ ගාස්තුව',
    'parcel.packageWeight': 'පැකේජ බර',
    'parcel.packageSize': 'පැකේජ ප්‍රමාණය',
    'parcel.specialInstructions': 'විශේෂ උපදෙස්',
    'parcel.status.pickedUp': 'ගෙන ගත්',
    'parcel.status.inTransit': 'ගමනේ',
    'parcel.status.outForDelivery': 'බෙදාහැරීමට පිටත්',
    'parcel.status.delivered': 'බෙදා හරින ලදි',
    
    // Status and messages
    'status.active': 'සක්‍රිය',
    'status.inactive': 'අක්‍රිය',
    'status.pending': 'පොරොත්තුවෙන්',
    'status.approved': 'අනුමත',
    'status.rejected': 'ප්‍රතික්ෂේප',
    'status.completed': 'සම්පූර්ණයි',
    'status.cancelled': 'අවලංගු',
    'status.online': 'අන්තර්ජාලීන',
    'status.offline': 'අන්තර්ජාලීන නොවේ',
    
    // Footer
    'footer.services': 'සේවා',
    'footer.partners': 'හවුල්කරුවන්',
    'footer.contact': 'අපව සම්බන්ධ කරන්න',
    'footer.accessibility': 'ප්‍රවේශ්‍යතාව',
    'footer.privacy': 'රහස්‍යතා ප්‍රතිපත්තිය',
    'footer.terms': 'සේවා කොන්දේසි',
    'footer.cookies': 'කුකීස්',
    'footer.copyright': '© 2024 Run Pick. සියලුම හිමිකම් ඇවිරිණි.',
    'footer.tagline': 'සෑම දෙයක්ම. සෑම තැනකම. එකවරම.',
    
    // Language selector
    'language.selector': 'භාෂාව',
    'language.english': 'English',
    'language.sinhala': 'සිංහල',
    'language.tamil': 'தமிழ்',
    
    // Buttons and actions
    'button.becomePartner': 'හවුල්කරුවෙකු වන්න',
    'button.signOut': 'ඉවත් වන්න',
    'button.approve': 'අනුමත කරන්න',
    'button.reject': 'ප්‍රතික්ෂේප කරන්න',
    'button.view': 'බලන්න',
    'button.manage': 'කළමනාකරණය කරන්න',
    'button.update': 'යාවත්කාලීන කරන්න',
    'button.refresh': 'නැවුම් කරන්න',
    
    // Time and dates
    'time.now': 'දැන්',
    'time.today': 'අද',
    'time.yesterday': 'ඊයේ',
    'time.thisWeek': 'මෙම සතිය',
    'time.thisMonth': 'මෙම මාසය',
    'time.ago': 'කට පෙර',
    'time.mins': 'මිනිත්තු',
    'time.hours': 'පැය',
    'time.days': 'දින',
  },
  
  ta: {
    // Navigation
    'nav.home': 'முகப்பு',
    'nav.taxi': 'டாக்ஸி',
    'nav.food': 'உணவு',
    'nav.parcel': 'பார்சல்',
    'nav.breakdown': 'பழுது',
    'nav.dashboard': 'டாஷ்போர்டு',
    'nav.lorry': 'லாரி',
    'nav.movers': 'போக்குவரத்து',
    'nav.supermarket': 'சூப்பர் மார்க்கெட்',
    'nav.gas': 'வாயு',
    'nav.bus': 'பேருந்து',
    'nav.jcb': 'ஜேசிபி',
    
    // Common
    'common.loading': 'ஏற்றுகிறது...',
    'common.submit': 'சமர்ப்பிக்கவும்',
    'common.cancel': 'ரத்து செய்',
    'common.save': 'சேமிக்கவும்',
    'common.edit': 'திருத்து',
    'common.delete': 'நீக்கு',
    'common.confirm': 'உறுதிப்படுத்து',
    'common.back': 'பின்',
    'common.next': 'அடுத்து',
    'common.previous': 'முந்தைய',
    'common.search': 'தேடல்',
    'common.filter': 'வடிகட்டி',
    'common.close': 'மூடு',
    'common.open': 'திற',
    'common.yes': 'ஆம்',
    'common.no': 'இல்லை',
    'common.viewAll': 'அனைத்தையும் பார்க்கவும்',
    'common.getStarted': 'ஆரம்பிக்கவும்',
    'common.learnMore': 'மேலும் அறிக',
    'common.tryNow': 'இப்போது முயற்சிக்கவும்',
    'common.bookNow': 'இப்போது புக் செய்யுங்கள்',
    'common.orderNow': 'இப்போது ஆர்டர் செய்யுங்கள்',
    'common.sendNow': 'இப்போது அனுப்பவும்',
    'common.success': 'வெற்றி',
    'common.error': 'பிழை',
    'common.warning': 'எச்சரிக்கை',
    'common.info': 'தகவல்',
    'common.comingSoon': 'விரைவில்',
    
    // Home page
    'home.title': 'ஸ்ரீலங்காவின் முன்னணி பல-சேவை தளம்',
    'home.subtitle': 'ஒரே ஆப்பில் ரைடுகள், உணவு விநியோகம், பார்சல் சேவைகள் மற்றும் பழுது உதவி பெறுங்கள்',
    'home.heroSubtitle': 'எல்லாம். எங்கும். ஒரே நேரத்தில்.',
    'home.services.taxi': 'டாக்ஸி ரைடுகள்',
    'home.services.taxi.desc': 'ஸ்ரீலங்கா முழுவதும் வேகமான, நம்பகமான ரைடுகள். இப்போது புக் செய்து பாதுகாப்பாக செல்லுங்கள்.',
    'home.services.food': 'உணவு விநியோகம்',
    'home.services.food.desc': 'அற்புதமான உணவகங்களைக் கண்டறியுங்கள். லைவ் ட்ராக்கிங் மற்றும் வேகமான விநியோகத்துடன் புதிய உணவு சுவையானது.',
    'home.services.parcel': 'பார்சல் விநியோகம்',
    'home.services.parcel.desc': 'எதையும், எங்கும் அனுப்புங்கள். பாதுகாப்பான பேக்கேஜிங், நேரடி கண்காணிப்பு மற்றும் வீட்டு வரை விநியோக உத்தரவாதம்.',
    'home.services.movers': 'போக்குவரத்து',
    'home.services.movers.desc': 'தொழில்முறை வீடு மற்றும் அலுவலக இடமாற்ற சேவைகள். அனுபவமிக்க குழு மற்றும் முழு காப்பீட்டு கவரேஜுடன் பாதுகாப்பான, நம்பகமான பொருட்கள் அகற்றல்.',
    'home.services.breakdown': 'பழுது சேவைகள்',
    'home.features.title': 'ஏன் Run Pick ஐ தேர்வு செய்ய வேண்டும்?',
    'home.features.reliable': 'நம்பகமான சேவை',
    'home.features.reliable.desc': 'சரிபார்க்கப்பட்ட ஓட்டுநர்கள் மற்றும் கூட்டாளர்களுடன் 24/7 கிடைக்கும் சேவைகள்',
    'home.features.tracking': 'நேரடி கண்காணிப்பு',
    'home.features.tracking.desc': 'உங்கள் ரைடு, உணவு ஆர்டர் அல்லது பார்சலை நேரடியாக கண்காணிக்கவும்',
    'home.features.payment': 'பாதுகாப்பான கட்டணம்',
    'home.features.payment.desc': 'பாதுகாப்பான பரிவர்த்தனைகளுடன் பல கட்டண விருப்பங்கள்',
    
    // Authentication
    'auth.welcome': 'Run Pick க்கு வரவேற்கிறோம்',
    'auth.subtitle': 'ஸ்ரீலங்காவுக்கான உங்கள் எல்லாம் ஆப்',
    'auth.signIn': 'உள்நுழைக',
    'auth.signUp': 'பதிவுசெய்க',
    'auth.signInTitle': 'மீண்டும் வரவேற்கிறோம்',
    'auth.signUpTitle': 'கணக்கு உருவாக்கவும்',
    'auth.signInSubtitle': 'தொடர உங்கள் கணக்கில் உள்நுழைக',
    'auth.signUpSubtitle': 'தொடங்க உங்கள் கணக்கை உருவாக்கவும்',
    'auth.email': 'மின்னஞ்சல்',
    'auth.password': 'கடவுச்சொல்',
    'auth.confirmPassword': 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
    'auth.name': 'முழு பெயர்',
    'auth.phone': 'தொலைபேசி எண்',
    'auth.role': 'கணக்கு வகை',
    'auth.forgotPassword': 'கடவுச்சொல்லை மறந்துவிட்டீர்களா?',
    'auth.noAccount': 'கணக்கு இல்லையா?',
    'auth.hasAccount': 'ஏற்கனவே கணக்கு உள்ளதா?',
    'auth.createAccount': 'கணக்கு உருவாக்கவும்',
    'auth.signInInstead': 'அதற்கு பதிலாக உள்நுழைக',
    'auth.signUpInstead': 'அதற்கு பதிலாக பதிவுசெய்க',
    'auth.roleCustomer': 'வாடிக்கையாளர்',
    'auth.roleDriver': 'ஓட்டுநர்',
    'auth.roleVendor': 'விற்பனையாளர்',
    'auth.roleAdmin': 'நிர்வாகி',
    'auth.roleCustomer.desc': 'ரைடுகளை புக் செய்யுங்கள், உணவு ஆர்டர் செய்யுங்கள், பார்சல்களை அனுப்புங்கள்',
    'auth.roleDriver.desc': 'பயணிகளை ஓட்டுங்கள், உணவு மற்றும் பார்சல்களை விநியோகிக்கவும்',
    'auth.roleVendor.desc': 'உணவகங்கள் மற்றும் உணவு விநியோகத்தை நிர்வகிக்கவும்',
    'auth.roleAdmin.desc': 'தளத்தின் செயல்பாடுகளை நிர்வகிக்கவும்',
    'auth.adminCode': 'நிர்வாகி ரகசிய குறியீடு',
    'auth.adminCode.placeholder': 'நிர்வாகி ரகசிய குறியீட்டை உள்ளிடவும்',
    'auth.adminCode.required': 'நிர்வாகி ரகசிய குறியீடு தேவை',
    'auth.error.invalidCredentials': 'தவறான மின்னஞ்சல் அல்லது கடவுச்சொல்',
    'auth.error.userExists': 'பயனர் ஏற்கனவே உள்ளார்',
    'auth.error.invalidAdmin': 'தவறான நிர்வாகி ரகசிய குறியீடு',
    
    // Dashboard - Customer
    'dashboard.customer.title': 'வாடிக்கையாளர் டாஷ்போர்டு',
    'dashboard.customer.subtitle': 'உங்கள் முன்பதிவுகள் மற்றும் ஆர்டர்களை நிர்வகிக்கவும்',
    'dashboard.customer.totalRides': 'மொத்த ரைடுகள்',
    'dashboard.customer.foodOrders': 'உணவு ஆர்டர்கள்',
    'dashboard.customer.parcelsSent': 'அனுப்பப்பட்ட பார்சல்கள்',
    'dashboard.customer.walletBalance': 'வாலட் நிலுவை',
    'dashboard.customer.recentActivity': 'சமீபத்திய செயல்பாடு',
    'dashboard.customer.favoriteRestaurants': 'விருப்பமான உணவகங்கள்',
    'dashboard.customer.frequentRoutes': 'அடிக்கடி செல்லும் வழிகள்',
    'dashboard.customer.bookRide': 'ரைடு புக் செய்யுங்கள்',
    'dashboard.customer.orderFood': 'உணவு ஆர்டர் செய்யுங்கள்',
    'dashboard.customer.sendParcel': 'பார்சல் அனுப்பவும்',
    
    // Dashboard - Driver
    'dashboard.driver.title': 'ஓட்டுநர் டாஷ்போர்டு',
    'dashboard.driver.subtitle': 'உங்கள் ரைடுகள் மற்றும் வருமானத்தை நிர்வகிக்கவும்',
    'dashboard.driver.todaysEarnings': 'இன்றைய வருமானம்',
    'dashboard.driver.completedRides': 'முடிக்கப்பட்ட ரைடுகள்',
    'dashboard.driver.rating': 'மதிப்பீடு',
    'dashboard.driver.thisWeek': 'இந்த வாரம்',
    'dashboard.driver.activeRequests': 'செயலில் உள்ள கோரிக்கைகள்',
    'dashboard.driver.recentTrips': 'சமீபத்திய பயணங்கள்',
    'dashboard.driver.goOnline': 'ஆன்லைனில் செல்லுங்கள்',
    'dashboard.driver.goOffline': 'ஆஃப்லைனில் செல்லுங்கள்',
    'dashboard.driver.acceptRequest': 'ஏற்றுக்கொள்',
    'dashboard.driver.declineRequest': 'மறுக்கவும்',
    'dashboard.driver.online': 'ஆன்லைன்',
    'dashboard.driver.offline': 'ஆஃப்லைன்',
    
    // Dashboard - Vendor
    'dashboard.vendor.title': 'விற்பனையாளர் டாஷ்போர்டு',
    'dashboard.vendor.subtitle': 'உங்கள் உணவகங்கள் மற்றும் ஆர்டர்களை நிர்வகிக்கவும்',
    'dashboard.vendor.totalRevenue': 'மொத்த வருமானம்',
    'dashboard.vendor.ordersToday': 'இன்றைய ஆர்டர்கள்',
    'dashboard.vendor.averageRating': 'சராசரி மதிப்பீடு',
    'dashboard.vendor.deliveryTime': 'விநியோக நேரம்',
    'dashboard.vendor.restaurants': 'எனது உணவகங்கள்',
    'dashboard.vendor.recentOrders': 'சமீபத்திய ஆர்டர்கள்',
    'dashboard.vendor.addRestaurant': 'உணவகம் சேர்க்கவும்',
    'dashboard.vendor.manageMenu': 'மெனுவை நிர்வகிக்கவும்',
    
    // Dashboard - Admin
    'dashboard.admin.title': 'நிர்வாகி டாஷ்போர்டு',
    'dashboard.admin.subtitle': 'தளத்தின் செயல்பாடுகளை நிர்வகிக்கவும்',
    'dashboard.admin.totalUsers': 'மொத்த பயனர்கள்',
    'dashboard.admin.activeDrivers': 'செயலில் உள்ள ஓட்டுநர்கள்',
    'dashboard.admin.totalRevenue': 'மொத்த வருமானம்',
    'dashboard.admin.commission': 'கமிஷன்',
    'dashboard.admin.recentActivity': 'சமீபத்திய செயல்பாடு',
    'dashboard.admin.pendingApprovals': 'நிலுவையில் உள்ள அனுமதிகள்',
    'dashboard.admin.systemStats': 'அமைப்பு புள்ளிவிவரங்கள்',
    'dashboard.admin.userManagement': 'பயனர் நிர்வாகம்',
    'dashboard.admin.driverApprovals': 'ஓட்டுநர் அனுமதிகள்',
    'dashboard.admin.vendorApprovals': 'விற்பனையாளர் அனுமதிகள்',
    
    // Ride booking
    'ride.title': 'ரைடு புக் செய்யுங்கள்',
    'ride.pickup': 'எடுக்கும் இடம்',
    'ride.destination': 'இலக்கு',
    'ride.currentLocation': 'தற்போதைய இடத்தைப் பயன்படுத்தவும்',
    'ride.chooseVehicle': 'வாகன வகையைத் தேர்ந்தெடுக்கவும்',
    'ride.availableDrivers': 'கிடைக்கும் ஓட்டுநர்கள்',
    'ride.confirmBooking': 'முன்பதிவை உறுதிப்படுத்தவும்',
    'ride.requestRide': 'ரைடு கோரவும்',
    'ride.booking': 'முன்பதிவு செய்கிறது...',
    'ride.estimatedFare': 'மதிப்பிடப்பட்ட கட்டணம்',
    'ride.duration': 'கால அளவு',
    'ride.distance': 'தூரம்',
    'ride.vehicleType.bike': 'மோட்டார் சைக்கிள்',
    'ride.vehicleType.tuktuk': 'டுக்-டுக்',
    'ride.vehicleType.car': 'கார்',
    'ride.vehicleType.van': 'வேன்',
    'ride.status.pending': 'நிலுவையில்',
    'ride.status.accepted': 'ஏற்றுக்கொள்ளப்பட்டது',
    'ride.status.arrived': 'ஓட்டுநர் வந்துவிட்டார்',
    'ride.status.started': 'பயணம் தொடங்கியது',
    'ride.status.completed': 'முடிக்கப்பட்டது',
    'ride.status.cancelled': 'ரத்து செய்யப்பட்டது',
    
    // Food delivery
    'food.title': 'உணவு விநியோகம்',
    'food.browseRestaurants': 'உணவகங்களை உலாவவும்',
    'food.orderHistory': 'ஆர்டர் வரலாறு',
    'food.favorites': 'விருப்பமானவை',
    'food.trackOrder': 'ஆர்டரை கண்காணிக்கவும்',
    'food.addToCart': 'கார்ட்டில் சேர்க்கவும்',
    'food.viewCart': 'கார்ட்டை பார்க்கவும்',
    'food.checkout': 'செக்அவுட்',
    'food.orderPlaced': 'ஆர்டர் செய்யப்பட்டது',
    'food.estimatedDelivery': 'மதிப்பிடப்பட்ட விநியோகம்',
    'food.restaurant.closed': 'உணவகம் மூடப்பட்டுள்ளது',
    'food.restaurant.open': 'இப்போது திறந்துள்ளது',
    'food.status.preparing': 'தயாரிக்கிறது',
    'food.status.ready': 'எடுக்க தயார்',
    'food.status.pickedUp': 'எடுக்கப்பட்டது',
    'food.status.delivered': 'விநியோகிக்கப்பட்டது',
    
    // Parcel delivery
    'parcel.title': 'பார்சல் விநியோகம்',
    'parcel.senderInfo': 'அனுப்புநர் தகவல்',
    'parcel.receiverInfo': 'பெறுநர் தகவல்',
    'parcel.packageDetails': 'பேக்கேஜ் விவரங்கள்',
    'parcel.deliveryOptions': 'விநியோக விருப்பங்கள்',
    'parcel.schedulePickup': 'எடுப்பதை திட்டமிடவும்',
    'parcel.trackParcel': 'பார்சலை கண்காணிக்கவும்',
    'parcel.deliveryFee': 'விநியோக கட்டணம்',
    'parcel.packageWeight': 'பேக்கேஜ் எடை',
    'parcel.packageSize': 'பேக்கேஜ் அளவு',
    'parcel.specialInstructions': 'சிறப்பு வழிமுறைகள்',
    'parcel.status.pickedUp': 'எடுக்கப்பட்டது',
    'parcel.status.inTransit': 'போக்குவரத்தில்',
    'parcel.status.outForDelivery': 'விநியோகத்திற்கு வெளியே',
    'parcel.status.delivered': 'விநியோகிக்கப்பட்டது',
    
    // Status and messages
    'status.active': 'செயலில்',
    'status.inactive': 'செயலற்றது',
    'status.pending': 'நிலுவையில்',
    'status.approved': 'அனுமதிக்கப்பட்டது',
    'status.rejected': 'நிராகரிக்கப்பட்டது',
    'status.completed': 'முடிக்கப்பட்டது',
    'status.cancelled': 'ரத்து செய்யப்பட்டது',
    'status.online': 'ஆன்லைன்',
    'status.offline': 'ஆஃப்லைன்',
    
    // Footer
    'footer.services': 'சேவைகள்',
    'footer.partners': 'கூட்டாளர்கள்',
    'footer.contact': 'எங்களை தொடர்பு கொள்ளுங்கள்',
    'footer.accessibility': 'அணுகல்',
    'footer.privacy': 'தனியுரிமை கொள்கை',
    'footer.terms': 'சேவை விதிமுறைகள்',
    'footer.cookies': 'குக்கீகள்',
    'footer.copyright': '© 2024 Run Pick. அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.',
    'footer.tagline': 'எல்லாம். எங்கும். ஒரே நேரத்தில்.',
    
    // Language selector
    'language.selector': 'மொழி',
    'language.english': 'English',
    'language.sinhala': 'සිංහල',
    'language.tamil': 'தமிழ்',
    
    // Buttons and actions
    'button.becomePartner': 'கூட்டாளராக மாறுங்கள்',
    'button.signOut': 'வெளியேறு',
    'button.approve': 'அனுமதிக்கவும்',
    'button.reject': 'நிராகரிக்கவும்',
    'button.view': 'பார்க்கவும்',
    'button.manage': 'நிர்வகிக்கவும்',
    'button.update': 'புதுப்பிக்கவும்',
    'button.refresh': 'புதுப்பிக்கவும்',
    
    // Time and dates
    'time.now': 'இப்போது',
    'time.today': 'இன்று',
    'time.yesterday': 'நேற்று',
    'time.thisWeek': 'இந்த வாரம்',
    'time.thisMonth': 'இந்த மாதம்',
    'time.ago': 'முன்பு',
    'time.mins': 'நிமிடங்கள்',
    'time.hours': 'மணிநேரங்கள்',
    'time.days': 'நாட்கள்',
  }
};

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState<Language>(() => {
    // Get language from localStorage or default to English
    const savedLanguage = localStorage.getItem('runpick_language') as Language;
    return savedLanguage || 'en';
  });

  // Save language preference to localStorage
  useEffect(() => {
    localStorage.setItem('runpick_language', currentLanguage);
  }, [currentLanguage]);

  const setLanguage = (language: Language) => {
    setCurrentLanguage(language);
  };

  const t = (key: string): string => {
    const translation = translations[currentLanguage][key as keyof typeof translations['en']];
    return translation || key; // Return key if translation not found
  };

  const value: LanguageContextType = {
    currentLanguage,
    setLanguage,
    t
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};